name       : libticonv
version    : 1.1.5
release    : 1
source     :
    - https://downloads.sourceforge.net/project/tilp/tilp2-linux/tilp2-1.18/libticonv-1.1.5.tar.bz2 : 316da6a73bf26b266dd23443882abc4c9fe7013edc3a53e5e301d525c2060878
license    : GPL-2.0-or-later
component  : programming.library
summary    : TiLP character conversion library
description: |
    This library is part of the TiLP project.
setup      : |
    %reconfigure --enable-iconv
build      : |
    %make
install    : |
    %make_install
